name: SerialKey
main: fr.skyost.serialkey.SerialKey
author: Skyost
version: 0.3
website: https://www.skyost.eu
commands:
  serialkey:
    description: Main command of SerialKey.
    aliases: [serial-key, sk]
    usage: /serialkey getkey.
permissions:
  serialkey.craft.key:
    default: true
    description: Allows you to craft a key.
  serialkey.craft.masterkey:
    default: op
    description: Allows you to craft a master key.
  serialkey.craft.keyclone:
    default: true
    description: Allows you to craft a clone of a key.
  serialkey.craft.bunchofkeys:
    default: true
    description: Allows you to craft a bunch of keys.
  serialkey.craft.padlockfinder:
    default: true
    description: Allows you to craft a padlock finder.
  serialkey.use.key:
    default: true
    description: Allows you to use a key.
  serialkey.use.masterkey:
    default: op
    description: Allows you to use a master key.
  serialkey.use.bunchofkeys:
    default: true
    description: Allows you to use a bunch of keys.
  serialkey.use.padlockfinder:
    default: true
    description: Allows you to use a padlock finder.
  serialkey.command.getkey:
    default: op
    description: Allows you to use /serialkey getkey.